### ISSUE TITLE
[Question] What File Icon Theme is used in the Preview Image for the theme?

### ISSUE THREAD

**Issue by johngagefaulkner** [hydralite/skyline#2]
> ![PreviewImage](https://i.imgur.com/3CiFSiN.png)

In that image, the `Skyline` theme is applied but all of the file type icons have their own correlated color. However, I applied the theme a few minutes ago and now all of mine are blue. (See below.) Do I need to change my File Icon Theme?

> ![MyImg](https://i.imgur.com/zpgWYOf.png)

**Comment by suptejas** [comment]
Do you have a GitHub Repository setup on your codebase?
